# Generated by Django 5.1.2 on 2024-10-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_remove_busketitems_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busketitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.product'),
        ),
    ]
