# Generated by Django 3.2.12 on 2024-09-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api_1', '0005_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_api_1.post'),
        ),
        migrations.AlterUniqueTogether(
            name='tagrelationship',
            unique_together={('post', 'tag')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='blog_api_1__post_id_4f71ed_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='blog_api_1__author__eb9919_idx'),
        ),
        migrations.AddIndex(
            model_name='tagrelationship',
            index=models.Index(fields=['post', 'tag'], name='blog_api_1__post_id_904e14_idx'),
        ),
    ]
